/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BluntRouteImport } from './routes/_blunt'
import { Route as BluntIndexRouteImport } from './routes/_blunt/index'
import { Route as BluntExpertiseRouteImport } from './routes/_blunt/expertise'
import { Route as BluntContactRouteImport } from './routes/_blunt/contact'
import { Route as BluntCareersRouteImport } from './routes/_blunt/careers'
import { Route as BluntAboutRouteImport } from './routes/_blunt/about'
import { Route as BluntWorkIndexRouteImport } from './routes/_blunt/work.index'
import { Route as BluntWorkSlugRouteImport } from './routes/_blunt/work.$slug'

const BluntRoute = BluntRouteImport.update({
  id: '/_blunt',
  getParentRoute: () => rootRouteImport,
} as any)
const BluntIndexRoute = BluntIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BluntRoute,
} as any)
const BluntExpertiseRoute = BluntExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => BluntRoute,
} as any)
const BluntContactRoute = BluntContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => BluntRoute,
} as any)
const BluntCareersRoute = BluntCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => BluntRoute,
} as any)
const BluntAboutRoute = BluntAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BluntRoute,
} as any)
const BluntWorkIndexRoute = BluntWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => BluntRoute,
} as any)
const BluntWorkSlugRoute = BluntWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => BluntRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BluntIndexRoute
  '/about': typeof BluntAboutRoute
  '/careers': typeof BluntCareersRoute
  '/contact': typeof BluntContactRoute
  '/expertise': typeof BluntExpertiseRoute
  '/work/$slug': typeof BluntWorkSlugRoute
  '/work/': typeof BluntWorkIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof BluntAboutRoute
  '/careers': typeof BluntCareersRoute
  '/contact': typeof BluntContactRoute
  '/expertise': typeof BluntExpertiseRoute
  '/': typeof BluntIndexRoute
  '/work/$slug': typeof BluntWorkSlugRoute
  '/work': typeof BluntWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_blunt': typeof BluntRouteWithChildren
  '/_blunt/about': typeof BluntAboutRoute
  '/_blunt/careers': typeof BluntCareersRoute
  '/_blunt/contact': typeof BluntContactRoute
  '/_blunt/expertise': typeof BluntExpertiseRoute
  '/_blunt/': typeof BluntIndexRoute
  '/_blunt/work/$slug': typeof BluntWorkSlugRoute
  '/_blunt/work/': typeof BluntWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/expertise'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/careers'
    | '/contact'
    | '/expertise'
    | '/'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/_blunt'
    | '/_blunt/about'
    | '/_blunt/careers'
    | '/_blunt/contact'
    | '/_blunt/expertise'
    | '/_blunt/'
    | '/_blunt/work/$slug'
    | '/_blunt/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BluntRoute: typeof BluntRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blunt': {
      id: '/_blunt'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BluntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blunt/': {
      id: '/_blunt/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BluntIndexRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/expertise': {
      id: '/_blunt/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof BluntExpertiseRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/contact': {
      id: '/_blunt/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof BluntContactRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/careers': {
      id: '/_blunt/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof BluntCareersRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/about': {
      id: '/_blunt/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof BluntAboutRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/work/': {
      id: '/_blunt/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof BluntWorkIndexRouteImport
      parentRoute: typeof BluntRoute
    }
    '/_blunt/work/$slug': {
      id: '/_blunt/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof BluntWorkSlugRouteImport
      parentRoute: typeof BluntRoute
    }
  }
}

interface BluntRouteChildren {
  BluntAboutRoute: typeof BluntAboutRoute
  BluntCareersRoute: typeof BluntCareersRoute
  BluntContactRoute: typeof BluntContactRoute
  BluntExpertiseRoute: typeof BluntExpertiseRoute
  BluntIndexRoute: typeof BluntIndexRoute
  BluntWorkSlugRoute: typeof BluntWorkSlugRoute
  BluntWorkIndexRoute: typeof BluntWorkIndexRoute
}

const BluntRouteChildren: BluntRouteChildren = {
  BluntAboutRoute: BluntAboutRoute,
  BluntCareersRoute: BluntCareersRoute,
  BluntContactRoute: BluntContactRoute,
  BluntExpertiseRoute: BluntExpertiseRoute,
  BluntIndexRoute: BluntIndexRoute,
  BluntWorkSlugRoute: BluntWorkSlugRoute,
  BluntWorkIndexRoute: BluntWorkIndexRoute,
}

const BluntRouteWithChildren = BluntRoute._addFileChildren(BluntRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BluntRoute: BluntRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
