/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VSlugRouteImport } from './routes/v/$slug'
import { Route as ShareShareTokenRouteImport } from './routes/share/$shareToken'
import { Route as OSlugRouteImport } from './routes/o/$slug'
import { Route as NsSlugRouteImport } from './routes/ns/$slug'
import { Route as NSlugRouteImport } from './routes/n/$slug'
import { Route as ISlugRouteImport } from './routes/i/$slug'
import { Route as CSlugRouteImport } from './routes/c/$slug'
import { Route as AuthedSigninRouteImport } from './routes/_authed/signin'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as OgOSlugRouteImport } from './routes/og/o.$slug'
import { Route as AuthedAppTasksIndexRouteImport } from './routes/_authed/_app/tasks/index'
import { Route as AuthedAppSpecsIndexRouteImport } from './routes/_authed/_app/specs/index'
import { Route as AuthedAppSettingsIndexRouteImport } from './routes/_authed/_app/settings/index'
import { Route as AuthedAppPortfolioIndexRouteImport } from './routes/_authed/_app/portfolio/index'
import { Route as AuthedAppOffertesIndexRouteImport } from './routes/_authed/_app/offertes/index'
import { Route as AuthedAppNdasIndexRouteImport } from './routes/_authed/_app/ndas/index'
import { Route as AuthedAppInvoicesIndexRouteImport } from './routes/_authed/_app/invoices/index'
import { Route as AuthedAppHabitsIndexRouteImport } from './routes/_authed/_app/habits/index'
import { Route as AuthedAppFeedbackIndexRouteImport } from './routes/_authed/_app/feedback/index'
import { Route as AuthedAppDashboardIndexRouteImport } from './routes/_authed/_app/dashboard/index'
import { Route as AuthedAppClientsIndexRouteImport } from './routes/_authed/_app/clients/index'
import { Route as AuthedAppBillingIndexRouteImport } from './routes/_authed/_app/billing/index'
import { Route as AuthedAppSpecsSpecIdRouteImport } from './routes/_authed/_app/specs/$specId'
import { Route as AuthedAppPortfolioItemIdRouteImport } from './routes/_authed/_app/portfolio/$itemId'
import { Route as AuthedAppOffertesOfferteIdRouteImport } from './routes/_authed/_app/offertes/$offerteId'
import { Route as AuthedAppNdasNdaIdRouteImport } from './routes/_authed/_app/ndas/$ndaId'
import { Route as AuthedAppInvoicesInvoiceIdRouteImport } from './routes/_authed/_app/invoices/$invoiceId'
import { Route as AuthedAppFeedbackProjectIdRouteImport } from './routes/_authed/_app/feedback/$projectId'
import { Route as AuthedAppClientsClientIdRouteImport } from './routes/_authed/_app/clients/$clientId'
import { Route as AuthedAppBillingBillingClientIdRouteImport } from './routes/_authed/_app/billing/$billingClientId'
import { Route as AuthedAppFeedbackProjectIdIndexRouteImport } from './routes/_authed/_app/feedback/$projectId.index'
import { Route as AuthedAppBoekhoudingRapportenIndexRouteImport } from './routes/_authed/_app/boekhouding/rapporten/index'
import { Route as AuthedAppBoekhoudingGrootboekIndexRouteImport } from './routes/_authed/_app/boekhouding/grootboek/index'
import { Route as AuthedAppFeedbackProjectIdReviewRouteImport } from './routes/_authed/_app/feedback/$projectId.review'
import { Route as AuthedAppFeedbackProjectIdInstallRouteImport } from './routes/_authed/_app/feedback/$projectId.install'
import { Route as AuthedAppBoekhoudingGrootboekEntryIdRouteImport } from './routes/_authed/_app/boekhouding/grootboek/$entryId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NsSlugRoute = NsSlugRouteImport.update({
  id: '/ns/$slug',
  path: '/ns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSigninRoute = AuthedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const OgOSlugRoute = OgOSlugRouteImport.update({
  id: '/og/o/$slug',
  path: '/og/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppTasksIndexRoute = AuthedAppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSpecsIndexRoute = AuthedAppSpecsIndexRouteImport.update({
  id: '/specs/',
  path: '/specs/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsIndexRoute = AuthedAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppPortfolioIndexRoute = AuthedAppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOffertesIndexRoute = AuthedAppOffertesIndexRouteImport.update({
  id: '/offertes/',
  path: '/offertes/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppNdasIndexRoute = AuthedAppNdasIndexRouteImport.update({
  id: '/ndas/',
  path: '/ndas/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInvoicesIndexRoute = AuthedAppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppHabitsIndexRoute = AuthedAppHabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppFeedbackIndexRoute = AuthedAppFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppDashboardIndexRoute = AuthedAppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppClientsIndexRoute = AuthedAppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBillingIndexRoute = AuthedAppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSpecsSpecIdRoute = AuthedAppSpecsSpecIdRouteImport.update({
  id: '/specs/$specId',
  path: '/specs/$specId',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppPortfolioItemIdRoute =
  AuthedAppPortfolioItemIdRouteImport.update({
    id: '/portfolio/$itemId',
    path: '/portfolio/$itemId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppOffertesOfferteIdRoute =
  AuthedAppOffertesOfferteIdRouteImport.update({
    id: '/offertes/$offerteId',
    path: '/offertes/$offerteId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppNdasNdaIdRoute = AuthedAppNdasNdaIdRouteImport.update({
  id: '/ndas/$ndaId',
  path: '/ndas/$ndaId',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInvoicesInvoiceIdRoute =
  AuthedAppInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppFeedbackProjectIdRoute =
  AuthedAppFeedbackProjectIdRouteImport.update({
    id: '/feedback/$projectId',
    path: '/feedback/$projectId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppClientsClientIdRoute =
  AuthedAppClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppBillingBillingClientIdRoute =
  AuthedAppBillingBillingClientIdRouteImport.update({
    id: '/billing/$billingClientId',
    path: '/billing/$billingClientId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppFeedbackProjectIdIndexRoute =
  AuthedAppFeedbackProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppFeedbackProjectIdRoute,
  } as any)
const AuthedAppBoekhoudingRapportenIndexRoute =
  AuthedAppBoekhoudingRapportenIndexRouteImport.update({
    id: '/boekhouding/rapporten/',
    path: '/boekhouding/rapporten/',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppBoekhoudingGrootboekIndexRoute =
  AuthedAppBoekhoudingGrootboekIndexRouteImport.update({
    id: '/boekhouding/grootboek/',
    path: '/boekhouding/grootboek/',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppFeedbackProjectIdReviewRoute =
  AuthedAppFeedbackProjectIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthedAppFeedbackProjectIdRoute,
  } as any)
const AuthedAppFeedbackProjectIdInstallRoute =
  AuthedAppFeedbackProjectIdInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => AuthedAppFeedbackProjectIdRoute,
  } as any)
const AuthedAppBoekhoudingGrootboekEntryIdRoute =
  AuthedAppBoekhoudingGrootboekEntryIdRouteImport.update({
    id: '/boekhouding/grootboek/$entryId',
    path: '/boekhouding/grootboek/$entryId',
    getParentRoute: () => AuthedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof AuthedSigninRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/n/$slug': typeof NSlugRoute
  '/ns/$slug': typeof NsSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v/$slug': typeof VSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/billing/$billingClientId': typeof AuthedAppBillingBillingClientIdRoute
  '/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/feedback/$projectId': typeof AuthedAppFeedbackProjectIdRouteWithChildren
  '/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/ndas/$ndaId': typeof AuthedAppNdasNdaIdRoute
  '/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/portfolio/$itemId': typeof AuthedAppPortfolioItemIdRoute
  '/specs/$specId': typeof AuthedAppSpecsSpecIdRoute
  '/billing/': typeof AuthedAppBillingIndexRoute
  '/clients/': typeof AuthedAppClientsIndexRoute
  '/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/feedback/': typeof AuthedAppFeedbackIndexRoute
  '/habits/': typeof AuthedAppHabitsIndexRoute
  '/invoices/': typeof AuthedAppInvoicesIndexRoute
  '/ndas/': typeof AuthedAppNdasIndexRoute
  '/offertes/': typeof AuthedAppOffertesIndexRoute
  '/portfolio/': typeof AuthedAppPortfolioIndexRoute
  '/settings/': typeof AuthedAppSettingsIndexRoute
  '/specs/': typeof AuthedAppSpecsIndexRoute
  '/tasks/': typeof AuthedAppTasksIndexRoute
  '/boekhouding/grootboek/$entryId': typeof AuthedAppBoekhoudingGrootboekEntryIdRoute
  '/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/feedback/$projectId/review': typeof AuthedAppFeedbackProjectIdReviewRoute
  '/boekhouding/grootboek/': typeof AuthedAppBoekhoudingGrootboekIndexRoute
  '/boekhouding/rapporten/': typeof AuthedAppBoekhoudingRapportenIndexRoute
  '/feedback/$projectId/': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof AuthedSigninRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/n/$slug': typeof NSlugRoute
  '/ns/$slug': typeof NsSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v/$slug': typeof VSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/billing/$billingClientId': typeof AuthedAppBillingBillingClientIdRoute
  '/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/ndas/$ndaId': typeof AuthedAppNdasNdaIdRoute
  '/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/portfolio/$itemId': typeof AuthedAppPortfolioItemIdRoute
  '/specs/$specId': typeof AuthedAppSpecsSpecIdRoute
  '/billing': typeof AuthedAppBillingIndexRoute
  '/clients': typeof AuthedAppClientsIndexRoute
  '/dashboard': typeof AuthedAppDashboardIndexRoute
  '/feedback': typeof AuthedAppFeedbackIndexRoute
  '/habits': typeof AuthedAppHabitsIndexRoute
  '/invoices': typeof AuthedAppInvoicesIndexRoute
  '/ndas': typeof AuthedAppNdasIndexRoute
  '/offertes': typeof AuthedAppOffertesIndexRoute
  '/portfolio': typeof AuthedAppPortfolioIndexRoute
  '/settings': typeof AuthedAppSettingsIndexRoute
  '/specs': typeof AuthedAppSpecsIndexRoute
  '/tasks': typeof AuthedAppTasksIndexRoute
  '/boekhouding/grootboek/$entryId': typeof AuthedAppBoekhoudingGrootboekEntryIdRoute
  '/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/feedback/$projectId/review': typeof AuthedAppFeedbackProjectIdReviewRoute
  '/boekhouding/grootboek': typeof AuthedAppBoekhoudingGrootboekIndexRoute
  '/boekhouding/rapporten': typeof AuthedAppBoekhoudingRapportenIndexRoute
  '/feedback/$projectId': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/signin': typeof AuthedSigninRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/n/$slug': typeof NSlugRoute
  '/ns/$slug': typeof NsSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/v/$slug': typeof VSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/_authed/_app/billing/$billingClientId': typeof AuthedAppBillingBillingClientIdRoute
  '/_authed/_app/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/_authed/_app/feedback/$projectId': typeof AuthedAppFeedbackProjectIdRouteWithChildren
  '/_authed/_app/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/_authed/_app/ndas/$ndaId': typeof AuthedAppNdasNdaIdRoute
  '/_authed/_app/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/_authed/_app/portfolio/$itemId': typeof AuthedAppPortfolioItemIdRoute
  '/_authed/_app/specs/$specId': typeof AuthedAppSpecsSpecIdRoute
  '/_authed/_app/billing/': typeof AuthedAppBillingIndexRoute
  '/_authed/_app/clients/': typeof AuthedAppClientsIndexRoute
  '/_authed/_app/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/_authed/_app/feedback/': typeof AuthedAppFeedbackIndexRoute
  '/_authed/_app/habits/': typeof AuthedAppHabitsIndexRoute
  '/_authed/_app/invoices/': typeof AuthedAppInvoicesIndexRoute
  '/_authed/_app/ndas/': typeof AuthedAppNdasIndexRoute
  '/_authed/_app/offertes/': typeof AuthedAppOffertesIndexRoute
  '/_authed/_app/portfolio/': typeof AuthedAppPortfolioIndexRoute
  '/_authed/_app/settings/': typeof AuthedAppSettingsIndexRoute
  '/_authed/_app/specs/': typeof AuthedAppSpecsIndexRoute
  '/_authed/_app/tasks/': typeof AuthedAppTasksIndexRoute
  '/_authed/_app/boekhouding/grootboek/$entryId': typeof AuthedAppBoekhoudingGrootboekEntryIdRoute
  '/_authed/_app/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/_authed/_app/feedback/$projectId/review': typeof AuthedAppFeedbackProjectIdReviewRoute
  '/_authed/_app/boekhouding/grootboek/': typeof AuthedAppBoekhoudingGrootboekIndexRoute
  '/_authed/_app/boekhouding/rapporten/': typeof AuthedAppBoekhoudingRapportenIndexRoute
  '/_authed/_app/feedback/$projectId/': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/c/$slug'
    | '/i/$slug'
    | '/n/$slug'
    | '/ns/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/v/$slug'
    | '/og/o/$slug'
    | '/billing/$billingClientId'
    | '/clients/$clientId'
    | '/feedback/$projectId'
    | '/invoices/$invoiceId'
    | '/ndas/$ndaId'
    | '/offertes/$offerteId'
    | '/portfolio/$itemId'
    | '/specs/$specId'
    | '/billing/'
    | '/clients/'
    | '/dashboard/'
    | '/feedback/'
    | '/habits/'
    | '/invoices/'
    | '/ndas/'
    | '/offertes/'
    | '/portfolio/'
    | '/settings/'
    | '/specs/'
    | '/tasks/'
    | '/boekhouding/grootboek/$entryId'
    | '/feedback/$projectId/install'
    | '/feedback/$projectId/review'
    | '/boekhouding/grootboek/'
    | '/boekhouding/rapporten/'
    | '/feedback/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/c/$slug'
    | '/i/$slug'
    | '/n/$slug'
    | '/ns/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/v/$slug'
    | '/og/o/$slug'
    | '/billing/$billingClientId'
    | '/clients/$clientId'
    | '/invoices/$invoiceId'
    | '/ndas/$ndaId'
    | '/offertes/$offerteId'
    | '/portfolio/$itemId'
    | '/specs/$specId'
    | '/billing'
    | '/clients'
    | '/dashboard'
    | '/feedback'
    | '/habits'
    | '/invoices'
    | '/ndas'
    | '/offertes'
    | '/portfolio'
    | '/settings'
    | '/specs'
    | '/tasks'
    | '/boekhouding/grootboek/$entryId'
    | '/feedback/$projectId/install'
    | '/feedback/$projectId/review'
    | '/boekhouding/grootboek'
    | '/boekhouding/rapporten'
    | '/feedback/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_app'
    | '/_authed/signin'
    | '/c/$slug'
    | '/i/$slug'
    | '/n/$slug'
    | '/ns/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/v/$slug'
    | '/og/o/$slug'
    | '/_authed/_app/billing/$billingClientId'
    | '/_authed/_app/clients/$clientId'
    | '/_authed/_app/feedback/$projectId'
    | '/_authed/_app/invoices/$invoiceId'
    | '/_authed/_app/ndas/$ndaId'
    | '/_authed/_app/offertes/$offerteId'
    | '/_authed/_app/portfolio/$itemId'
    | '/_authed/_app/specs/$specId'
    | '/_authed/_app/billing/'
    | '/_authed/_app/clients/'
    | '/_authed/_app/dashboard/'
    | '/_authed/_app/feedback/'
    | '/_authed/_app/habits/'
    | '/_authed/_app/invoices/'
    | '/_authed/_app/ndas/'
    | '/_authed/_app/offertes/'
    | '/_authed/_app/portfolio/'
    | '/_authed/_app/settings/'
    | '/_authed/_app/specs/'
    | '/_authed/_app/tasks/'
    | '/_authed/_app/boekhouding/grootboek/$entryId'
    | '/_authed/_app/feedback/$projectId/install'
    | '/_authed/_app/feedback/$projectId/review'
    | '/_authed/_app/boekhouding/grootboek/'
    | '/_authed/_app/boekhouding/rapporten/'
    | '/_authed/_app/feedback/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CSlugRoute: typeof CSlugRoute
  ISlugRoute: typeof ISlugRoute
  NSlugRoute: typeof NSlugRoute
  NsSlugRoute: typeof NsSlugRoute
  OSlugRoute: typeof OSlugRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
  VSlugRoute: typeof VSlugRoute
  OgOSlugRoute: typeof OgOSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ns/$slug': {
      id: '/ns/$slug'
      path: '/ns/$slug'
      fullPath: '/ns/$slug'
      preLoaderRoute: typeof NsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/signin': {
      id: '/_authed/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthedSigninRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/og/o/$slug': {
      id: '/og/o/$slug'
      path: '/og/o/$slug'
      fullPath: '/og/o/$slug'
      preLoaderRoute: typeof OgOSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app/tasks/': {
      id: '/_authed/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedAppTasksIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/specs/': {
      id: '/_authed/_app/specs/'
      path: '/specs'
      fullPath: '/specs/'
      preLoaderRoute: typeof AuthedAppSpecsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings/': {
      id: '/_authed/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedAppSettingsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/portfolio/': {
      id: '/_authed/_app/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthedAppPortfolioIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/offertes/': {
      id: '/_authed/_app/offertes/'
      path: '/offertes'
      fullPath: '/offertes/'
      preLoaderRoute: typeof AuthedAppOffertesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/ndas/': {
      id: '/_authed/_app/ndas/'
      path: '/ndas'
      fullPath: '/ndas/'
      preLoaderRoute: typeof AuthedAppNdasIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/invoices/': {
      id: '/_authed/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/habits/': {
      id: '/_authed/_app/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof AuthedAppHabitsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/': {
      id: '/_authed/_app/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthedAppFeedbackIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/dashboard/': {
      id: '/_authed/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedAppDashboardIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/clients/': {
      id: '/_authed/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedAppClientsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/billing/': {
      id: '/_authed/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthedAppBillingIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/specs/$specId': {
      id: '/_authed/_app/specs/$specId'
      path: '/specs/$specId'
      fullPath: '/specs/$specId'
      preLoaderRoute: typeof AuthedAppSpecsSpecIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/portfolio/$itemId': {
      id: '/_authed/_app/portfolio/$itemId'
      path: '/portfolio/$itemId'
      fullPath: '/portfolio/$itemId'
      preLoaderRoute: typeof AuthedAppPortfolioItemIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/offertes/$offerteId': {
      id: '/_authed/_app/offertes/$offerteId'
      path: '/offertes/$offerteId'
      fullPath: '/offertes/$offerteId'
      preLoaderRoute: typeof AuthedAppOffertesOfferteIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/ndas/$ndaId': {
      id: '/_authed/_app/ndas/$ndaId'
      path: '/ndas/$ndaId'
      fullPath: '/ndas/$ndaId'
      preLoaderRoute: typeof AuthedAppNdasNdaIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/invoices/$invoiceId': {
      id: '/_authed/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedAppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/$projectId': {
      id: '/_authed/_app/feedback/$projectId'
      path: '/feedback/$projectId'
      fullPath: '/feedback/$projectId'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/clients/$clientId': {
      id: '/_authed/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthedAppClientsClientIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/billing/$billingClientId': {
      id: '/_authed/_app/billing/$billingClientId'
      path: '/billing/$billingClientId'
      fullPath: '/billing/$billingClientId'
      preLoaderRoute: typeof AuthedAppBillingBillingClientIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/$projectId/': {
      id: '/_authed/_app/feedback/$projectId/'
      path: '/'
      fullPath: '/feedback/$projectId/'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdIndexRouteImport
      parentRoute: typeof AuthedAppFeedbackProjectIdRoute
    }
    '/_authed/_app/boekhouding/rapporten/': {
      id: '/_authed/_app/boekhouding/rapporten/'
      path: '/boekhouding/rapporten'
      fullPath: '/boekhouding/rapporten/'
      preLoaderRoute: typeof AuthedAppBoekhoudingRapportenIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/boekhouding/grootboek/': {
      id: '/_authed/_app/boekhouding/grootboek/'
      path: '/boekhouding/grootboek'
      fullPath: '/boekhouding/grootboek/'
      preLoaderRoute: typeof AuthedAppBoekhoudingGrootboekIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/$projectId/review': {
      id: '/_authed/_app/feedback/$projectId/review'
      path: '/review'
      fullPath: '/feedback/$projectId/review'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdReviewRouteImport
      parentRoute: typeof AuthedAppFeedbackProjectIdRoute
    }
    '/_authed/_app/feedback/$projectId/install': {
      id: '/_authed/_app/feedback/$projectId/install'
      path: '/install'
      fullPath: '/feedback/$projectId/install'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdInstallRouteImport
      parentRoute: typeof AuthedAppFeedbackProjectIdRoute
    }
    '/_authed/_app/boekhouding/grootboek/$entryId': {
      id: '/_authed/_app/boekhouding/grootboek/$entryId'
      path: '/boekhouding/grootboek/$entryId'
      fullPath: '/boekhouding/grootboek/$entryId'
      preLoaderRoute: typeof AuthedAppBoekhoudingGrootboekEntryIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppFeedbackProjectIdRouteChildren {
  AuthedAppFeedbackProjectIdInstallRoute: typeof AuthedAppFeedbackProjectIdInstallRoute
  AuthedAppFeedbackProjectIdReviewRoute: typeof AuthedAppFeedbackProjectIdReviewRoute
  AuthedAppFeedbackProjectIdIndexRoute: typeof AuthedAppFeedbackProjectIdIndexRoute
}

const AuthedAppFeedbackProjectIdRouteChildren: AuthedAppFeedbackProjectIdRouteChildren =
  {
    AuthedAppFeedbackProjectIdInstallRoute:
      AuthedAppFeedbackProjectIdInstallRoute,
    AuthedAppFeedbackProjectIdReviewRoute:
      AuthedAppFeedbackProjectIdReviewRoute,
    AuthedAppFeedbackProjectIdIndexRoute: AuthedAppFeedbackProjectIdIndexRoute,
  }

const AuthedAppFeedbackProjectIdRouteWithChildren =
  AuthedAppFeedbackProjectIdRoute._addFileChildren(
    AuthedAppFeedbackProjectIdRouteChildren,
  )

interface AuthedAppRouteChildren {
  AuthedAppBillingBillingClientIdRoute: typeof AuthedAppBillingBillingClientIdRoute
  AuthedAppClientsClientIdRoute: typeof AuthedAppClientsClientIdRoute
  AuthedAppFeedbackProjectIdRoute: typeof AuthedAppFeedbackProjectIdRouteWithChildren
  AuthedAppInvoicesInvoiceIdRoute: typeof AuthedAppInvoicesInvoiceIdRoute
  AuthedAppNdasNdaIdRoute: typeof AuthedAppNdasNdaIdRoute
  AuthedAppOffertesOfferteIdRoute: typeof AuthedAppOffertesOfferteIdRoute
  AuthedAppPortfolioItemIdRoute: typeof AuthedAppPortfolioItemIdRoute
  AuthedAppSpecsSpecIdRoute: typeof AuthedAppSpecsSpecIdRoute
  AuthedAppBillingIndexRoute: typeof AuthedAppBillingIndexRoute
  AuthedAppClientsIndexRoute: typeof AuthedAppClientsIndexRoute
  AuthedAppDashboardIndexRoute: typeof AuthedAppDashboardIndexRoute
  AuthedAppFeedbackIndexRoute: typeof AuthedAppFeedbackIndexRoute
  AuthedAppHabitsIndexRoute: typeof AuthedAppHabitsIndexRoute
  AuthedAppInvoicesIndexRoute: typeof AuthedAppInvoicesIndexRoute
  AuthedAppNdasIndexRoute: typeof AuthedAppNdasIndexRoute
  AuthedAppOffertesIndexRoute: typeof AuthedAppOffertesIndexRoute
  AuthedAppPortfolioIndexRoute: typeof AuthedAppPortfolioIndexRoute
  AuthedAppSettingsIndexRoute: typeof AuthedAppSettingsIndexRoute
  AuthedAppSpecsIndexRoute: typeof AuthedAppSpecsIndexRoute
  AuthedAppTasksIndexRoute: typeof AuthedAppTasksIndexRoute
  AuthedAppBoekhoudingGrootboekEntryIdRoute: typeof AuthedAppBoekhoudingGrootboekEntryIdRoute
  AuthedAppBoekhoudingGrootboekIndexRoute: typeof AuthedAppBoekhoudingGrootboekIndexRoute
  AuthedAppBoekhoudingRapportenIndexRoute: typeof AuthedAppBoekhoudingRapportenIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBillingBillingClientIdRoute: AuthedAppBillingBillingClientIdRoute,
  AuthedAppClientsClientIdRoute: AuthedAppClientsClientIdRoute,
  AuthedAppFeedbackProjectIdRoute: AuthedAppFeedbackProjectIdRouteWithChildren,
  AuthedAppInvoicesInvoiceIdRoute: AuthedAppInvoicesInvoiceIdRoute,
  AuthedAppNdasNdaIdRoute: AuthedAppNdasNdaIdRoute,
  AuthedAppOffertesOfferteIdRoute: AuthedAppOffertesOfferteIdRoute,
  AuthedAppPortfolioItemIdRoute: AuthedAppPortfolioItemIdRoute,
  AuthedAppSpecsSpecIdRoute: AuthedAppSpecsSpecIdRoute,
  AuthedAppBillingIndexRoute: AuthedAppBillingIndexRoute,
  AuthedAppClientsIndexRoute: AuthedAppClientsIndexRoute,
  AuthedAppDashboardIndexRoute: AuthedAppDashboardIndexRoute,
  AuthedAppFeedbackIndexRoute: AuthedAppFeedbackIndexRoute,
  AuthedAppHabitsIndexRoute: AuthedAppHabitsIndexRoute,
  AuthedAppInvoicesIndexRoute: AuthedAppInvoicesIndexRoute,
  AuthedAppNdasIndexRoute: AuthedAppNdasIndexRoute,
  AuthedAppOffertesIndexRoute: AuthedAppOffertesIndexRoute,
  AuthedAppPortfolioIndexRoute: AuthedAppPortfolioIndexRoute,
  AuthedAppSettingsIndexRoute: AuthedAppSettingsIndexRoute,
  AuthedAppSpecsIndexRoute: AuthedAppSpecsIndexRoute,
  AuthedAppTasksIndexRoute: AuthedAppTasksIndexRoute,
  AuthedAppBoekhoudingGrootboekEntryIdRoute:
    AuthedAppBoekhoudingGrootboekEntryIdRoute,
  AuthedAppBoekhoudingGrootboekIndexRoute:
    AuthedAppBoekhoudingGrootboekIndexRoute,
  AuthedAppBoekhoudingRapportenIndexRoute:
    AuthedAppBoekhoudingRapportenIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedSigninRoute: typeof AuthedSigninRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedSigninRoute: AuthedSigninRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CSlugRoute: CSlugRoute,
  ISlugRoute: ISlugRoute,
  NSlugRoute: NSlugRoute,
  NsSlugRoute: NsSlugRoute,
  OSlugRoute: OSlugRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
  VSlugRoute: VSlugRoute,
  OgOSlugRoute: OgOSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
