/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingV1RouteImport } from './routes/_marketing/v1'
import { Route as MarketingFullRouteImport } from './routes/_marketing/full'
import { Route as MarketingWorkV1SlugRouteImport } from './routes/_marketing/work-v1.$slug'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingV1Route = MarketingV1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFullRoute = MarketingFullRouteImport.update({
  id: '/full',
  path: '/full',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingWorkV1SlugRoute = MarketingWorkV1SlugRouteImport.update({
  id: '/work-v1/$slug',
  path: '/work-v1/$slug',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingRouteWithChildren
  '/full': typeof MarketingFullRoute
  '/v1': typeof MarketingV1Route
  '/work-v1/$slug': typeof MarketingWorkV1SlugRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingRouteWithChildren
  '/full': typeof MarketingFullRoute
  '/v1': typeof MarketingV1Route
  '/work-v1/$slug': typeof MarketingWorkV1SlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/full': typeof MarketingFullRoute
  '/_marketing/v1': typeof MarketingV1Route
  '/_marketing/work-v1/$slug': typeof MarketingWorkV1SlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/full' | '/v1' | '/work-v1/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/full' | '/v1' | '/work-v1/$slug'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/full'
    | '/_marketing/v1'
    | '/_marketing/work-v1/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/v1': {
      id: '/_marketing/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof MarketingV1RouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/full': {
      id: '/_marketing/full'
      path: '/full'
      fullPath: '/full'
      preLoaderRoute: typeof MarketingFullRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/work-v1/$slug': {
      id: '/_marketing/work-v1/$slug'
      path: '/work-v1/$slug'
      fullPath: '/work-v1/$slug'
      preLoaderRoute: typeof MarketingWorkV1SlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingFullRoute: typeof MarketingFullRoute
  MarketingV1Route: typeof MarketingV1Route
  MarketingWorkV1SlugRoute: typeof MarketingWorkV1SlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingFullRoute: MarketingFullRoute,
  MarketingV1Route: MarketingV1Route,
  MarketingWorkV1SlugRoute: MarketingWorkV1SlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
