/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as ShareShareTokenRouteImport } from './routes/share/$shareToken'
import { Route as OSlugRouteImport } from './routes/o/$slug'
import { Route as ISlugRouteImport } from './routes/i/$slug'
import { Route as CSlugRouteImport } from './routes/c/$slug'
import { Route as MarketingFullRouteImport } from './routes/_marketing/full'
import { Route as AuthedSigninRouteImport } from './routes/_authed/signin'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as OgOSlugRouteImport } from './routes/og/o.$slug'
import { Route as MarketingWorkSlugRouteImport } from './routes/_marketing/work.$slug'
import { Route as AuthedAppTasksIndexRouteImport } from './routes/_authed/_app/tasks/index'
import { Route as AuthedAppSettingsIndexRouteImport } from './routes/_authed/_app/settings/index'
import { Route as AuthedAppPortfolioIndexRouteImport } from './routes/_authed/_app/portfolio/index'
import { Route as AuthedAppOffertesIndexRouteImport } from './routes/_authed/_app/offertes/index'
import { Route as AuthedAppInvoicesIndexRouteImport } from './routes/_authed/_app/invoices/index'
import { Route as AuthedAppFeedbackIndexRouteImport } from './routes/_authed/_app/feedback/index'
import { Route as AuthedAppDashboardIndexRouteImport } from './routes/_authed/_app/dashboard/index'
import { Route as AuthedAppClientsIndexRouteImport } from './routes/_authed/_app/clients/index'
import { Route as AuthedAppOffertesOfferteIdRouteImport } from './routes/_authed/_app/offertes/$offerteId'
import { Route as AuthedAppInvoicesInvoiceIdRouteImport } from './routes/_authed/_app/invoices/$invoiceId'
import { Route as AuthedAppFeedbackProjectIdRouteImport } from './routes/_authed/_app/feedback/$projectId'
import { Route as AuthedAppClientsClientIdRouteImport } from './routes/_authed/_app/clients/$clientId'
import { Route as AuthedAppBackupSplatRouteImport } from './routes/_authed/_app/backup/$'
import { Route as AuthedAppFeedbackProjectIdIndexRouteImport } from './routes/_authed/_app/feedback/$projectId.index'
import { Route as AuthedAppFeedbackProjectIdInstallRouteImport } from './routes/_authed/_app/feedback/$projectId.install'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFullRoute = MarketingFullRouteImport.update({
  id: '/full',
  path: '/full',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthedSigninRoute = AuthedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const OgOSlugRoute = OgOSlugRouteImport.update({
  id: '/og/o/$slug',
  path: '/og/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingWorkSlugRoute = MarketingWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthedAppTasksIndexRoute = AuthedAppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsIndexRoute = AuthedAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppPortfolioIndexRoute = AuthedAppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOffertesIndexRoute = AuthedAppOffertesIndexRouteImport.update({
  id: '/offertes/',
  path: '/offertes/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInvoicesIndexRoute = AuthedAppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppFeedbackIndexRoute = AuthedAppFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppDashboardIndexRoute = AuthedAppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppClientsIndexRoute = AuthedAppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOffertesOfferteIdRoute =
  AuthedAppOffertesOfferteIdRouteImport.update({
    id: '/offertes/$offerteId',
    path: '/offertes/$offerteId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppInvoicesInvoiceIdRoute =
  AuthedAppInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppFeedbackProjectIdRoute =
  AuthedAppFeedbackProjectIdRouteImport.update({
    id: '/feedback/$projectId',
    path: '/feedback/$projectId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppClientsClientIdRoute =
  AuthedAppClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppBackupSplatRoute = AuthedAppBackupSplatRouteImport.update({
  id: '/backup/$',
  path: '/backup/$',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppFeedbackProjectIdIndexRoute =
  AuthedAppFeedbackProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppFeedbackProjectIdRoute,
  } as any)
const AuthedAppFeedbackProjectIdInstallRoute =
  AuthedAppFeedbackProjectIdInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => AuthedAppFeedbackProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/signin': typeof AuthedSigninRoute
  '/full': typeof MarketingFullRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/work/$slug': typeof MarketingWorkSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/backup/$': typeof AuthedAppBackupSplatRoute
  '/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/feedback/$projectId': typeof AuthedAppFeedbackProjectIdRouteWithChildren
  '/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/clients/': typeof AuthedAppClientsIndexRoute
  '/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/feedback/': typeof AuthedAppFeedbackIndexRoute
  '/invoices/': typeof AuthedAppInvoicesIndexRoute
  '/offertes/': typeof AuthedAppOffertesIndexRoute
  '/portfolio/': typeof AuthedAppPortfolioIndexRoute
  '/settings/': typeof AuthedAppSettingsIndexRoute
  '/tasks/': typeof AuthedAppTasksIndexRoute
  '/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/feedback/$projectId/': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/signin': typeof AuthedSigninRoute
  '/full': typeof MarketingFullRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/work/$slug': typeof MarketingWorkSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/backup/$': typeof AuthedAppBackupSplatRoute
  '/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/clients': typeof AuthedAppClientsIndexRoute
  '/dashboard': typeof AuthedAppDashboardIndexRoute
  '/feedback': typeof AuthedAppFeedbackIndexRoute
  '/invoices': typeof AuthedAppInvoicesIndexRoute
  '/offertes': typeof AuthedAppOffertesIndexRoute
  '/portfolio': typeof AuthedAppPortfolioIndexRoute
  '/settings': typeof AuthedAppSettingsIndexRoute
  '/tasks': typeof AuthedAppTasksIndexRoute
  '/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/feedback/$projectId': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/signin': typeof AuthedSigninRoute
  '/_marketing/full': typeof MarketingFullRoute
  '/c/$slug': typeof CSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/o/$slug': typeof OSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/work/$slug': typeof MarketingWorkSlugRoute
  '/og/o/$slug': typeof OgOSlugRoute
  '/_authed/_app/backup/$': typeof AuthedAppBackupSplatRoute
  '/_authed/_app/clients/$clientId': typeof AuthedAppClientsClientIdRoute
  '/_authed/_app/feedback/$projectId': typeof AuthedAppFeedbackProjectIdRouteWithChildren
  '/_authed/_app/invoices/$invoiceId': typeof AuthedAppInvoicesInvoiceIdRoute
  '/_authed/_app/offertes/$offerteId': typeof AuthedAppOffertesOfferteIdRoute
  '/_authed/_app/clients/': typeof AuthedAppClientsIndexRoute
  '/_authed/_app/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/_authed/_app/feedback/': typeof AuthedAppFeedbackIndexRoute
  '/_authed/_app/invoices/': typeof AuthedAppInvoicesIndexRoute
  '/_authed/_app/offertes/': typeof AuthedAppOffertesIndexRoute
  '/_authed/_app/portfolio/': typeof AuthedAppPortfolioIndexRoute
  '/_authed/_app/settings/': typeof AuthedAppSettingsIndexRoute
  '/_authed/_app/tasks/': typeof AuthedAppTasksIndexRoute
  '/_authed/_app/feedback/$projectId/install': typeof AuthedAppFeedbackProjectIdInstallRoute
  '/_authed/_app/feedback/$projectId/': typeof AuthedAppFeedbackProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/full'
    | '/c/$slug'
    | '/i/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/work/$slug'
    | '/og/o/$slug'
    | '/backup/$'
    | '/clients/$clientId'
    | '/feedback/$projectId'
    | '/invoices/$invoiceId'
    | '/offertes/$offerteId'
    | '/clients/'
    | '/dashboard/'
    | '/feedback/'
    | '/invoices/'
    | '/offertes/'
    | '/portfolio/'
    | '/settings/'
    | '/tasks/'
    | '/feedback/$projectId/install'
    | '/feedback/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/full'
    | '/c/$slug'
    | '/i/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/work/$slug'
    | '/og/o/$slug'
    | '/backup/$'
    | '/clients/$clientId'
    | '/invoices/$invoiceId'
    | '/offertes/$offerteId'
    | '/clients'
    | '/dashboard'
    | '/feedback'
    | '/invoices'
    | '/offertes'
    | '/portfolio'
    | '/settings'
    | '/tasks'
    | '/feedback/$projectId/install'
    | '/feedback/$projectId'
  id:
    | '__root__'
    | '/_authed'
    | '/_marketing'
    | '/_authed/_app'
    | '/_authed/signin'
    | '/_marketing/full'
    | '/c/$slug'
    | '/i/$slug'
    | '/o/$slug'
    | '/share/$shareToken'
    | '/_marketing/'
    | '/_marketing/work/$slug'
    | '/og/o/$slug'
    | '/_authed/_app/backup/$'
    | '/_authed/_app/clients/$clientId'
    | '/_authed/_app/feedback/$projectId'
    | '/_authed/_app/invoices/$invoiceId'
    | '/_authed/_app/offertes/$offerteId'
    | '/_authed/_app/clients/'
    | '/_authed/_app/dashboard/'
    | '/_authed/_app/feedback/'
    | '/_authed/_app/invoices/'
    | '/_authed/_app/offertes/'
    | '/_authed/_app/portfolio/'
    | '/_authed/_app/settings/'
    | '/_authed/_app/tasks/'
    | '/_authed/_app/feedback/$projectId/install'
    | '/_authed/_app/feedback/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  CSlugRoute: typeof CSlugRoute
  ISlugRoute: typeof ISlugRoute
  OSlugRoute: typeof OSlugRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
  OgOSlugRoute: typeof OgOSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/full': {
      id: '/_marketing/full'
      path: '/full'
      fullPath: '/full'
      preLoaderRoute: typeof MarketingFullRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_authed/signin': {
      id: '/_authed/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthedSigninRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/og/o/$slug': {
      id: '/og/o/$slug'
      path: '/og/o/$slug'
      fullPath: '/og/o/$slug'
      preLoaderRoute: typeof OgOSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/work/$slug': {
      id: '/_marketing/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof MarketingWorkSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_authed/_app/tasks/': {
      id: '/_authed/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedAppTasksIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings/': {
      id: '/_authed/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedAppSettingsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/portfolio/': {
      id: '/_authed/_app/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthedAppPortfolioIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/offertes/': {
      id: '/_authed/_app/offertes/'
      path: '/offertes'
      fullPath: '/offertes/'
      preLoaderRoute: typeof AuthedAppOffertesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/invoices/': {
      id: '/_authed/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/': {
      id: '/_authed/_app/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthedAppFeedbackIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/dashboard/': {
      id: '/_authed/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedAppDashboardIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/clients/': {
      id: '/_authed/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedAppClientsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/offertes/$offerteId': {
      id: '/_authed/_app/offertes/$offerteId'
      path: '/offertes/$offerteId'
      fullPath: '/offertes/$offerteId'
      preLoaderRoute: typeof AuthedAppOffertesOfferteIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/invoices/$invoiceId': {
      id: '/_authed/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedAppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/$projectId': {
      id: '/_authed/_app/feedback/$projectId'
      path: '/feedback/$projectId'
      fullPath: '/feedback/$projectId'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/clients/$clientId': {
      id: '/_authed/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthedAppClientsClientIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/backup/$': {
      id: '/_authed/_app/backup/$'
      path: '/backup/$'
      fullPath: '/backup/$'
      preLoaderRoute: typeof AuthedAppBackupSplatRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feedback/$projectId/': {
      id: '/_authed/_app/feedback/$projectId/'
      path: '/'
      fullPath: '/feedback/$projectId/'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdIndexRouteImport
      parentRoute: typeof AuthedAppFeedbackProjectIdRoute
    }
    '/_authed/_app/feedback/$projectId/install': {
      id: '/_authed/_app/feedback/$projectId/install'
      path: '/install'
      fullPath: '/feedback/$projectId/install'
      preLoaderRoute: typeof AuthedAppFeedbackProjectIdInstallRouteImport
      parentRoute: typeof AuthedAppFeedbackProjectIdRoute
    }
  }
}

interface AuthedAppFeedbackProjectIdRouteChildren {
  AuthedAppFeedbackProjectIdInstallRoute: typeof AuthedAppFeedbackProjectIdInstallRoute
  AuthedAppFeedbackProjectIdIndexRoute: typeof AuthedAppFeedbackProjectIdIndexRoute
}

const AuthedAppFeedbackProjectIdRouteChildren: AuthedAppFeedbackProjectIdRouteChildren =
  {
    AuthedAppFeedbackProjectIdInstallRoute:
      AuthedAppFeedbackProjectIdInstallRoute,
    AuthedAppFeedbackProjectIdIndexRoute: AuthedAppFeedbackProjectIdIndexRoute,
  }

const AuthedAppFeedbackProjectIdRouteWithChildren =
  AuthedAppFeedbackProjectIdRoute._addFileChildren(
    AuthedAppFeedbackProjectIdRouteChildren,
  )

interface AuthedAppRouteChildren {
  AuthedAppBackupSplatRoute: typeof AuthedAppBackupSplatRoute
  AuthedAppClientsClientIdRoute: typeof AuthedAppClientsClientIdRoute
  AuthedAppFeedbackProjectIdRoute: typeof AuthedAppFeedbackProjectIdRouteWithChildren
  AuthedAppInvoicesInvoiceIdRoute: typeof AuthedAppInvoicesInvoiceIdRoute
  AuthedAppOffertesOfferteIdRoute: typeof AuthedAppOffertesOfferteIdRoute
  AuthedAppClientsIndexRoute: typeof AuthedAppClientsIndexRoute
  AuthedAppDashboardIndexRoute: typeof AuthedAppDashboardIndexRoute
  AuthedAppFeedbackIndexRoute: typeof AuthedAppFeedbackIndexRoute
  AuthedAppInvoicesIndexRoute: typeof AuthedAppInvoicesIndexRoute
  AuthedAppOffertesIndexRoute: typeof AuthedAppOffertesIndexRoute
  AuthedAppPortfolioIndexRoute: typeof AuthedAppPortfolioIndexRoute
  AuthedAppSettingsIndexRoute: typeof AuthedAppSettingsIndexRoute
  AuthedAppTasksIndexRoute: typeof AuthedAppTasksIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBackupSplatRoute: AuthedAppBackupSplatRoute,
  AuthedAppClientsClientIdRoute: AuthedAppClientsClientIdRoute,
  AuthedAppFeedbackProjectIdRoute: AuthedAppFeedbackProjectIdRouteWithChildren,
  AuthedAppInvoicesInvoiceIdRoute: AuthedAppInvoicesInvoiceIdRoute,
  AuthedAppOffertesOfferteIdRoute: AuthedAppOffertesOfferteIdRoute,
  AuthedAppClientsIndexRoute: AuthedAppClientsIndexRoute,
  AuthedAppDashboardIndexRoute: AuthedAppDashboardIndexRoute,
  AuthedAppFeedbackIndexRoute: AuthedAppFeedbackIndexRoute,
  AuthedAppInvoicesIndexRoute: AuthedAppInvoicesIndexRoute,
  AuthedAppOffertesIndexRoute: AuthedAppOffertesIndexRoute,
  AuthedAppPortfolioIndexRoute: AuthedAppPortfolioIndexRoute,
  AuthedAppSettingsIndexRoute: AuthedAppSettingsIndexRoute,
  AuthedAppTasksIndexRoute: AuthedAppTasksIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedSigninRoute: typeof AuthedSigninRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedSigninRoute: AuthedSigninRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface MarketingRouteChildren {
  MarketingFullRoute: typeof MarketingFullRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingWorkSlugRoute: typeof MarketingWorkSlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingFullRoute: MarketingFullRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingWorkSlugRoute: MarketingWorkSlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  CSlugRoute: CSlugRoute,
  ISlugRoute: ISlugRoute,
  OSlugRoute: OSlugRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
  OgOSlugRoute: OgOSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
